# 一行100文字まで
line-length = 100
# インデントは4スペース
indent-width = 4


# python 3.11
target-version = "py311"


[lint]
select = [
    "E",    # pycodestyle error
    "F",    # Pyflakes
    "W",    # pycodestyle warning
    "I",    # isort
    "B",    # flake8-bugbear
    "N"     # pep8-naming
]

# 除外するエラー
ignore = ["E201", "E202", "E225", "E226"]
# ruff --fix で自動修正できるエラー
fixable = ["E4", "E7", "E9", "F", "I"]

[lint.isort]
combine-as-imports = true
detect-same-package = false
force-sort-within-sections = true


[format]
# ダブルクォーテーションで統一.
quote-style = "double"

# インデントはスペースのみ.
indent-style = "space"

# 末行の改行を入れる.
line-ending = "auto"
