import type { Message } from '~/libs/types/message';

export const dummyMessages: Message[] = [
  {
    id: '1',
    app: 'discord',
    sender_image: 'https://avatars.githubusercontent.com/u/1',
    sender_name: 'discord-user1',
    content: 'dummy message1',
    message_link: 'xxx',
    sentiment: 'positive',
    priority: 'low',
    send_at: '2021-09-01',
  },
  {
    id: '2',
    app: 'slack',
    sender_image: 'https://avatars.githubusercontent.com/u/2',
    sender_name: 'slack-user1',
    content: 'dummy message2',
    message_link: 'xxx',
    sentiment: 'negative',
    priority: 'medium',
    send_at: '2021-09-02',
  },
  {
    id: '3',
    app: 'discord',
    sender_image: 'https://avatars.githubusercontent.com/u/3',
    sender_name: 'discord-user2',
    content: 'dummy message3',
    message_link: 'xxx',
    sentiment: 'positive',
    priority: 'high',
    send_at: '2021-09-03',
  },
  {
    id: '4',
    app: 'slack',
    sender_image: 'https://avatars.githubusercontent.com/u/4',
    sender_name: 'slack-user2',
    content: 'dummy message4',
    message_link: 'xxx',
    sentiment: 'negative',
    priority: 'urgent',
    send_at: '2021-09-04',
  },
  {
    id: '5',
    app: 'discord',
    sender_image: 'https://avatars.githubusercontent.com/u/5',
    sender_name: 'discord-user3',
    content: 'dummy message5',
    message_link: 'xxx',
    sentiment: 'positive',
    priority: 'critical',
    send_at: '2021-09-05',
  },
];
