---
name: Build Discord
on: 
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "packages/discord/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc #v4
      - name: build and push
        working-directory: packages/discord
        run: |
          docker build . -t all-in-api-discord --platform linux/amd64
