---
name: ECR push
on: 
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "packages/api/**"

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc #v4
      - uses: aws-actions/configure-aws-credentials@bd1354327e55c2330d56537b3ac2006a8d97c566 #v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::451153100141:role/All_In_Backend_API_CI"

      -  name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@08fda13c2502925256496fadb53b7718f48b28c5 #v2

      - name: build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: "all_in_api"
          TAG: "latest"

        working-directory: packages/api
        run: |
          ecr_path=${{ env.REGISTRY }}/${{ env.REPO }}:${{ env.TAG }}
          docker build . -t $ecr_path --platform linux/amd64
          docker push $ecr_path
