name: Refresh Slack Token
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */11 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc #v4

      - uses: aws-actions/configure-aws-credentials@bd1354327e55c2330d56537b3ac2006a8d97c566 #v4
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: "arn:aws:iam::451153100141:role/All_In_Backend_API_CI"

      - name: setup go
        uses: actions/setup-go@df1a11710ed378b187f40c71eb3d6c08d82e7108 # v5

      - name: refresh
        working-directory: .github/ci
        env:
          SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
          SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
        run: |
          go run slack_token_rotation.go

